// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

#define PI_WR_BIT 21
#define PI_RD_BIT 20
#define PI_CS1_BIT 17
#define PI_D7_BIT 13
#define PI_D6_BIT 12
#define PI_D5_BIT 11
#define PI_D4_BIT 10
#define PI_D3_BIT 9
#define PI_D2_BIT 8
#define PI_D1_BIT 7
#define PI_D0_BIT 6

// ------- //
// fcppu_w //
// ------- //

#define fcppu_w_wrap_target 0
#define fcppu_w_wrap 4

static const uint16_t fcppu_w_program_instructions[] = {
            //     .wrap_target
    0x2015, //  0: wait   0 gpio, 21                 
    0x00c4, //  1: jmp    pin, 4                     
    0x2095, //  2: wait   1 gpio, 21                 
    0x4000, //  3: in     pins, 32                   
    0x2095, //  4: wait   1 gpio, 21                 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program fcppu_w_program = {
    .instructions = fcppu_w_program_instructions,
    .length = 5,
    .origin = -1,
};

static inline pio_sm_config fcppu_w_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + fcppu_w_wrap_target, offset + fcppu_w_wrap);
    return c;
}
#endif

// ------- //
// fcppu_r //
// ------- //

#define fcppu_r_wrap_target 1
#define fcppu_r_wrap 5

static const uint16_t fcppu_r_program_instructions[] = {
    0xa0e3, //  0: mov    osr, null                  
            //     .wrap_target
    0x2014, //  1: wait   0 gpio, 20                 
    0x00c5, //  2: jmp    pin, 5                     
    0xc007, //  3: irq    nowait 7                   
    0x6008, //  4: out    pins, 8                    
    0x2094, //  5: wait   1 gpio, 20                 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program fcppu_r_program = {
    .instructions = fcppu_r_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config fcppu_r_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + fcppu_r_wrap_target, offset + fcppu_r_wrap);
    return c;
}
#endif

// --------- //
// fcppu_dir //
// --------- //

#define fcppu_dir_wrap_target 0
#define fcppu_dir_wrap 8

static const uint16_t fcppu_dir_program_instructions[] = {
            //     .wrap_target
    0x20c7, //  0: wait   1 irq, 7                   
    0xa0e3, //  1: mov    osr, null                  
    0x00c4, //  2: jmp    pin, 4                     
    0xa0eb, //  3: mov    osr, !null                 
    0xc047, //  4: irq    clear 7                    
    0x6088, //  5: out    pindirs, 8                 
    0x2094, //  6: wait   1 gpio, 20                 
    0xa0e3, //  7: mov    osr, null                  
    0x6088, //  8: out    pindirs, 8                 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program fcppu_dir_program = {
    .instructions = fcppu_dir_program_instructions,
    .length = 9,
    .origin = -1,
};

static inline pio_sm_config fcppu_dir_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + fcppu_dir_wrap_target, offset + fcppu_dir_wrap);
    return c;
}
#endif

// --------- //
// fcppu_rna //
// --------- //

#define fcppu_rna_wrap_target 1
#define fcppu_rna_wrap 5

static const uint16_t fcppu_rna_program_instructions[] = {
    0xa02b, //  0: mov    x, !null                   
            //     .wrap_target
    0x2014, //  1: wait   0 gpio, 20                 
    0x00c5, //  2: jmp    pin, 5                     
    0xa0c9, //  3: mov    isr, !x                    
    0x0045, //  4: jmp    x--, 5                     
    0x2094, //  5: wait   1 gpio, 20                 
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program fcppu_rna_program = {
    .instructions = fcppu_rna_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config fcppu_rna_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + fcppu_rna_wrap_target, offset + fcppu_rna_wrap);
    return c;
}


#endif

