;/// @file strver.h
;/// @brief The version string, regenerated by m.BAT on every build.
;/// @ingroup gamerom
;///
;/// One `DRAW_STRING2` line. Unlike the boot ROM's `dbdate.h`, this carries a
;/// hand-set version and no timestamp, so rebuilding does not by itself change the
;/// ROM. @see @ref build_pipeline
	DRAW_STRING2 " 2026 V1.00" 
